name: OpenFaaS CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull OpenFaaS Templates
      run: faas-cli template pull

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Install OpenFaaS CLI
      run: curl -sSL https://cli.openfaas.com | sh

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve